version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_fintrack
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: FINTRACK_DB
      MYSQL_USER: myuser
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data:

# -----------------------------------------------------------------------------

# version: '3.8'

# services:
#   # Banco de Dados MariaDB
#   mariadb:
#     image: mariadb:latest
#     container_name: mariadb_fintrack
#     restart: always
#     environment:
#       MARIADB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
#       MARIADB_DATABASE: fintrack_db
#       MARIADB_USER: fintrack_user
#       MARIADB_PASSWORD: ${MYSQL_PASSWORD}
#     ports:
#       - "3306:3306"
#     volumes:
#       - mariadb_data:/var/lib/mysql

#   # Backend ASP.NET Core
#   backend:
#     build:
#       context: ../FinTrack_API
#       dockerfile: Dockerfile
#     container_name: backend_fintrack
#     restart: always
#     environment:
#       ConnectionStrings__DefaultConnection: "Server=mariadb;Database=fintrackdb;User=fintrackuser;Password=fintrackpassword;"
#     ports:
#       - "5000:5000"
#       - "5001:5001"
#     depends_on:
#       - mariadb

#   # Frontend Vue.js
#   frontend:
#     build:
#       context: ../FinTrack
#       dockerfile: Dockerfile
#     container_name: frontend_fintrack
#     restart: always
#     ports:
#       - "8080:8080"
#     depends_on:
#       - backend

# volumes:
#   mariadb_data:
